name: 'Downloading PSRule Configuration File'
description: 'Downloading PSRule Configuration File'
inputs:
  inputPath: 
    description: 'inputPath required for PSRule action to define where the Bicep Deployment is stored'
    required: true
    default: '.'

runs:
  using: "composite"
  steps:
    - run: echo "${{ github.action_path }}" >> $GITHUB_PATH
      shell: bash
    - run: chmod +x ${{ github.action_path }}/psrule_configuration.sh
      shell: bash
    - run: psrule_configuration.sh
      shell: bash

    - name: Run PSRule analysis
      uses: microsoft/ps-rule@v2.9.0
      with:
        version: '1.11.1'
        modules: 'PSRule.Rules.Azure'
        inputPath: ${{inputs.inputPath}}
        source: '.'  
      