name: 'Downloading PSRule Configuration File'
description: 'Downloading PSRule Configuration File'
runs:
  using: "composite"
  steps:
    - name: 'Testing'
      run: ./psrule_configuration.sh
      shell: bash
      